trigger:
- main

pool:
  name: MyPersonalPC
  demands:
    - Agent.Name -equals ThinkpadE14
parameters:
- name: browserName
  displayName: 'Browser Name'
  type: string
  default: 'chrome'
  values:
  - 'chrome'
  - 'chromeheadless'
  - 'edge'
  - 'firefox'

- name: profile
  displayName: 'Profile'
  type: string
  default: 'Regression'
  values:
  - 'Regression'
  - 'ErrorValidation'

variables: 
- group: Email_Secrets
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test -P${{ parameters.profile }} -Dbrowser=${{ parameters.browserName }}'

- script: |
    echo "Copying HTML report to artifact staging directory"
    copy "reports\index.html" "$(Build.ArtifactStagingDirectory)\index.html"
  displayName: 'Copy HTML Report'
  condition: always()

- task: SendEmail@1
  condition: always()
  inputs:
    To: 'nsr.kpma@outlook.com'
    From: 'nsr01734@gmail.com'
    Subject: 'Selenium Test Automation Report'
    Body: |
      Hi Team,
      Please find the Selenium test automation report in the attachments.
      Thanks
      Nirmal
    BodyAsHtml: false
    AddAttachment: true
    Attachment: '$(Build.ArtifactStagingDirectory)/index.html'
    SmtpServer: 'smtp.gmail.com'
    SmtpUsername: '$(SMTP_USER_NAME)'
    SmtpPassword: '$(SMTP_PASSWORD)'